- name: kubectl create secret generic ceph-secret1 --type="kubernetes.io/rbd" --from-literal=key='{{cat.stdout_lines[0]}}'
  command: kubectl --kubeconfig={{PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml create secret generic ceph-secret1 --type="kubernetes.io/rbd" --from-literal=key='{{cat.stdout_lines[0]}}'


- name: kubectl create secret generic ceph-secret-kube1 --type="kubernetes.io/rbd" --from-literal=key='{{cat.stdout_lines[0]}}' --namespace=default
  command: kubectl --kubeconfig={{PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml create secret generic ceph-secret-kube1 --type="kubernetes.io/rbd" --from-literal=key='{{cat.stdout_lines[0]}}' --namespace=default


- name: Deleting already existing claim
  command: kubectl --kubeconfig={{PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml delete pvc {{Ceph_Claim_name}}
  ignore_errors: true

- name: Grep Ceph Persistent volume if already created kubectl get pv | grep {{Ceph_Claim_name}} | cut -d ' ' -f 1
  shell: kubectl --kubeconfig={{PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml get pv | grep {{Ceph_Claim_name}} | cut -d ' ' -f 1
  ignore_errors: true
  register: cat

- debug: var=cat.stdout_lines[0]

- name: Deleting already existing Ceph Persistant volume( kubectl delete pv {{cat.stdout_lines[0]}} )
  command: kubectl --kubeconfig={{PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml delete pv {{cat.stdout_lines[0]}}
  ignore_errors: true

- name: edit storage name in ceph-vc.yml
  lineinfile:
       dest: "{{SRC_PACKAGE_PATH}}/packages/source/ceph-vc.yml"
       regexp: 'storage:'
       line: '      storage: {{Ceph_storage}}'

- name: modified claim name in "ceph-vc.yml"
  lineinfile:
       dest: "{{SRC_PACKAGE_PATH}}/packages/source/ceph-vc.yml"
       regexp: 'name:'
       line: '  name: {{Ceph_Claim_name}}'


- name: edit ip in ceph-storage-fast_rbd.yml
  lineinfile:
       dest: "{{SRC_PACKAGE_PATH}}/packages/source/ceph-storage-fast_rbd.yml"
       regexp: 'monitors:'
       line: '  monitors: {{ceph_controller_ip}}:6789'

- name: creating storage class
  command: kubectl --kubeconfig={{PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml create -f "{{SRC_PACKAGE_PATH}}/packages/source/ceph-storage-fast_rbd.yml" --namespace=default
  register: cat
  ignore_errors: true
- debug: var=cat.stdout_lines

- name: creating claim
  command: kubectl --kubeconfig={{PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml create -f "{{SRC_PACKAGE_PATH}}/packages/source/ceph-vc.yml" --namespace=default
  register: cat
- debug: var=cat.stdout_lines

