# Copyright 2019 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---
- hosts: all

  gather_facts: no

  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - debug:
      var: second_storage

  - name: install parted
    apt:
      name: apt

  - name: "sudo parted -s {{ item }} mklabel gpt mkpart primary xfs 0% 100%"
    command: "sudo parted -s {{ item }} mklabel gpt mkpart primary xfs 0% 100%"
    with_items: "{{ second_storage }}"

  - name: "sudo mkfs.xfs -f {{ item }}"
    command: "sudo mkfs.xfs -f {{ item }}"
    with_items: "{{ second_storage }}"

  - name: "sudo fdisk -s {{ item }}"
    command: "sudo fdisk -s {{ item }}"
    with_items: "{{ second_storage }}"

  - name: "sudo blkid -o value -s TYPE {{ item }}"
    command: "sudo blkid -o value -s TYPE {{ item }}"
    with_items: "{{ second_storage }}"
