- name: configure monitor node - ceph-deploy new {{ ceph_mon }}
  command: ceph-deploy --username root new {{ ceph_mon }}
  args:
    chdir: "{{ PROJ_ARTIFACT_DIR }}/cluster-ceph"

- name: edit ceph.conf file
  lineinfile:
    dest: "{{ PROJ_ARTIFACT_DIR }}/cluster-ceph/ceph.conf"
    line: "osd pool default size = 1"

- name: install ceph packages to {{ ceph_all }}
  command: ceph-deploy --username root install {{ ceph_all }}
  args:
    chdir: "{{ PROJ_ARTIFACT_DIR }}/cluster-ceph"

- name: Create monitor keyringfile for monitor nodes
  command: ceph-deploy --overwrite-conf --username root mon create-initial
  args:
    chdir: "{{ PROJ_ARTIFACT_DIR }}/cluster-ceph"

- name: gather keyring files file on all nodes
  command: ceph-deploy --username root gatherkeys {{ ceph_mon }}
  args:
    chdir: "{{ PROJ_ARTIFACT_DIR }}/cluster-ceph"

- debug: var=ceph_target
- include: prepare_disk.yaml hostname={{ osd_item.hostname }} storage={{ osd_item.second_storage }}
  with_items: "{{ ceph_target }}"
  when:  osd_item.node_type == "ceph_osd"
  loop_control:
    loop_var: osd_item

- name: configure ceph admin keyring
  command: ceph-deploy --username root admin {{ ceph_all }}
  args:
    chdir: "{{ PROJ_ARTIFACT_DIR }}/cluster-ceph"
