---
- hosts: localhost

  tasks:
    - set_fact:
        ceph_target: "{{ceph_hosts | from_yaml }}"

    - debug:
        var: ceph_target

    - name: Add all instance private IPs to host group
      add_host:
          hostname: "{{ item.ip }}"
          ansible_ssh_user: "{{item.user}}"
          ansible_ssh_pass: "{{item.password}}"
          groups: ceph_hosts_group
      with_items: "{{ ceph_target }}"


    - name: check if keys present in host
      stat:
        path: /root/.ssh/id_rsa
      register: stat_result

    - name: keys generation
      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      when: stat_result.stat.exists == False

    - name: copy the public keys
      command: cat /root/.ssh/id_rsa.pub
      register: id
    - debug:
        var: id.stdout
    - set_fact:
        ceph_hosts_group: "{{hostvars[inventory_hostname].groups.ceph_hosts_group}}"
    - debug:
        var: ceph_hosts_group

    - name: edit /etc/hosts file
      lineinfile:
          dest: /etc/hosts
          line: "{{item.ip}} {{item.hostname}}"
      with_items: "{{ ceph_target }}"

    - name: add to known hosts
      shell: ssh-keyscan "{{ item.hostname }}" >> /root/.ssh/known_hosts
      with_items: "{{ ceph_target }}"

    - block:
       - include: ceph_set_hostname.yaml ceph_hostname={{item.hostname}} ceph_ip={{item.ip}}
         with_items: "{{ ceph_target }}"

