- debug:
    var: ceph_target

- name: Deleting secret ceph-secret1
  command: kubectl --kubeconfig={{ PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml delete secret ceph-secret1
  ignore_errors: true

- name: Deleting secret ceph-secret-kube1
  command: kubectl --kubeconfig={{ PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml delete secret ceph-secret-kube1
  ignore_errors: true

- name: deleting already existing storage class
  command: kubectl --kubeconfig={{ PROJ_ARTIFACT_DIR }}/node-kubeconfig.yaml delete sc fast-rbd2
  ignore_errors: true

- name: ceph-deploy purge {{ceph_all}}
  become: yes
  become_method: sudo
  become_user: root
  command: ceph-deploy --username root purge {{ceph_all}}
  ignore_errors: true

- name: ceph-deploy --username root purgedata {{ceph_all}}
  become: yes
  become_method: sudo
  become_user: root
  command: ceph-deploy --username root purgedata {{ceph_all}}
  ignore_errors: true

- name: ceph-deploy forgetkeys
  become: yes
  become_method: sudo
  become_user: root
  command: ceph-deploy --username root forgetkeys
  ignore_errors: true

- name: deleting already existing file
  become: yes
  become_method: sudo
  become_user: root
  file:
    state: absent
    dest: /var/lib/ceph/osd
  ignore_errors: true
