# Copyright 2018 ARICENT HOLDINGS LUXEMBOURG SARL and Cable Television
# Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is responsible for deploying Aricent_Iaas environments and
# Kubernetes Services
---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no

  tasks:
  - name: K8SN | upgrade aptitude
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: K8SN | install required sw pkgs
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common' ]

  - name: K8SN | docker gpg key add
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: K8SN | key fingerprint
    command: apt-key fingerprint 0EBFCD88

  - name: K8SN | apt source list add for docker pkg
    apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

  - name: K8SN | apt update
    command: apt update

  - name: K8SN | install docker-ce
    command: apt install docker-ce= "{{ docker_ce_ver }}"

  - name: K8SN | start docker
    command: systemctl start docker

  - name: K8SN | enable docker
    command: systemctl enable docker

