###########################################################################
# Copyright 2017 ARICENT HOLDINGS LUXEMBOURG SARL. and
# Cable Television Laboratories, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###########################################################################


---

- hosts: localhost
  become: true
  vars_files:
    - "{{ VARIABLE_FILE }}"
    - "{{ PROXY_DATA_FILE }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
    
    - name: copying "{{ PROJECT_PATH }}{{Project_name}}/inventory.cfg" to "{{KUBESPRAY_PATH}}kubespray/inventory/sample/inventory.cfg"
      copy: src="{{ PROJECT_PATH }}{{Project_name}}/inventory.cfg" dest="{{KUBESPRAY_PATH}}kubespray/inventory/sample/inventory.cfg"
    - name: copying "{{ PROJECT_PATH }}{{Project_name}}/k8s-cluster.yml" to "{{KUBESPRAY_PATH}}kubespray/inventory/sample/group_vars/k8s-cluster.yml"
      copy: src="{{ PROJECT_PATH }}{{Project_name}}/k8s-cluster.yml" dest="{{KUBESPRAY_PATH}}kubespray/inventory/sample/group_vars/k8s-cluster.yml"
    - name: copying "{{ PROJECT_PATH }}{{Project_name}}/all.yml" to "{{KUBESPRAY_PATH}}kubespray/inventory/sample/group_vars/all.yml"
      copy: src="{{ PROJECT_PATH }}{{Project_name}}/all.yml" dest="{{KUBESPRAY_PATH}}kubespray/inventory/sample/group_vars/all.yml"

    - name: edit reset.yaml
      replace:
        dest: "{{KUBESPRAY_PATH}}kubespray/reset.yml"
        regexp: 'default: "no"'
        replace: 'default: "yes"'
        backup: no

    - name: Reset/Remove kubernet cluster|logs redirect to /var/log/kubernetes_kubespray.log
      shell: ansible-playbook -i inventory/sample/inventory.cfg -u root -e ansible_ssh_user=root -b reset.yml >>/var/log/kubernetes_kubespray.log 
      args:
         chdir: "{{KUBESPRAY_PATH}}kubespray/"
    - name: install ansible=2.3.1.0
      pip:
       name: ansible
       version: 2.3.1.0

    - name: Clean path
      file:
        state: absent
        path: /var/lib/cni/
      ignore_errors: yes	 
