#!/bin/bash

# disable SSH
systemctl stop sshd

# disable automatic updates
sed -i 's/APT::Periodic::Update-Package-Lists "1"/APT::Periodic::Update-Package-Lists "0"/' /etc/apt/apt.conf.d/10periodic

#TODO select a different default kernel
KERNEL="4.15.0-50-generic"

# Install lowlatency kernel and set power governor for servers with accelerators
# gpu device id for NVIDIA:P4000 = 10de:1bb1
# gpu device id for NVIDIA:P1000 = 10de:1cb1
gpu_list=(
        '10de:1bb1'
        '10de:1cb1'
        '10de:1b80'
        '10de:10f0'
        )

while read -r line ; do
  for item in $gpu_list
    do
      if [ "$line" == "$item" ]; then
        echo "Found GPU device id $line. Installing lowlatency kernel..."
        KERNEL="4.15.0-50-lowlatency"
        break
      fi
    done
done < <(lspci -n | grep 10de | awk '{print $3}')

export DEBIAN_FRONTEND=noninteractive
unset  DEBIAN_HAS_FRONTEND
unset  DEBCONF_REDIR
unset  DEBCONF_OLD_FD_BASE
apt-get update
apt-get purge -y grub\*
apt-get install -q -y -f linux-headers-$KERNEL
apt-get install -q -y -f linux-image-$KERNEL
apt-get install -q -y -f cpufrequtils grub-efi
apt-get autoremove -y
echo 'GOVERNOR="performance"' | tee /etc/default/cpufrequtils
/etc/init.d/cpufrequtils restart
systemctl stop ondemand
systemctl disable ondemand

# OVS_DPDK
OVS_DPDK_FLAG="OFF"
if [ $OVS_DPDK_FLAG == "ON" ]
then
  lspci | grep -i Mellanox >/dev/null
  if [ $? -eq 0 ]
  then
    # install dpdk packages
    apt-get update
    apt-get install -q -y openvswitch-switch-dpdk --fix-missing
    echo "Installed :openvswitch-switch-dpdk"
    update-alternatives --set ovs-vswitchd /usr/lib/openvswitch-switch-dpdk/ovs-vswitchd-dpdk
    echo "update-alternatives :ovs-vswitchd"
    sleep 10
    systemctl restart openvswitch-switch.service
    echo "openvswitch-switch.service restarted..."

    # update grub
    sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT.*/GRUB_CMDLINE_LINUX_DEFAULT="maybe-ubiquity iommu=pt intel_iommu=on default_hugepagesz=1G hugepagesz=1G hugepages=16"/' /etc/default/grub
    echo "grub update done : hugepages"

    # mount/fstab.
    echo " # OVS DPDK: " >> /etc/fstab
    echo "none /dev/hugepages hugetlbfs" >> /etc/fstab
    echo "fstab : updation done"
  fi
fi
# End of OVS_DPDK

if [ $KERNEL == "4.15.0-50-lowlatency" ]
then
  sed -i 's/GRUB_DEFAULT=0/GRUB_DEFAULT="1>2"/' /etc/default/grub
fi

update-grub

touch /var/log/drp-boot-complete
