apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-rbd2
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.16.141.12:6789
  adminId: admin
  adminSecretName: ceph-secret1
  pool: kube
  userSecretName: ceph-secret-kube1

